got all preliminary testcases to pass for p2

diff --git a/p2/testAll b/p2/testAll
--- a/p2/testAll
+++ b/p2/testAll
@@ -1,14 +1,21 @@
 #!/opt/homebrew/bin/bash
+#LEEEEEROOOYYY JENKINSSSSS
+if [ "$1" = "p1" ]; then
+    TEST_DIR="./p1_testcases"
+    EXPECTED_OUTCOMES_FILE="expectedResults_p1.txt"
+elif [ "$1" = "p2" ]; then
+    TEST_DIR="./p2_testcases"
+    EXPECTED_OUTCOMES_FILE="expectedResults_p2.txt"
+else
+    echo "Invalid parameter. Please use 'p1' or 'p2'."
+    exit 1
+fi
 
 if [[ $(make --dry-run -s) ]]
 then
   echo "make thinks the interpreter is out of date and needs to be re-built"
   exit 1
 fi
-
-TEST_DIR="./🧪🧪🧪🧪🧪🧪"
-
-EXPECTED_OUTCOMES_FILE="expectedResults.txt"
 
 passedCount=0
 failedCount=0
@@ -23,7 +30,6 @@ for test_file in "$TEST_DIR"/*
 do
 
     filename=$(basename "$test_file")
-
 
     ./planModified "$test_file" > /dev/null 2>&1
     result=$?
